export const quotes = [
  "Some days you don't need answers, You need honesty with yourself, And the courage to sit with it.",
  "Growth begins the moment You stop running from discomfort And start listening to what it's teaching.",
  "You are not lost, You are simply between versions Of who you used to be and who you're becoming.",
  "Not every heavy feeling is a problem, Some are signals asking For care instead of judgment.",
  "Your pace is allowed to change, Life is not a race, It is a relationship with time.",
  "Healing doesn't mean forgetting the pain, It means learning How to live without letting it lead.",
  "Sometimes strength looks like pushing forward, Sometimes it looks like resting Without guilt.",
  "You don't need to fix everything today, Some things heal Simply by being acknowledged.",
  "Progress is quiet most days, It happens when no one is watching, Especially when you keep showing up.",
  "Being gentle with yourself Is not lowering your standards, It is raising your awareness.",
  "Your mind deserves the same patience You give to others When they are struggling.",
  "You are allowed to change your priorities When your inner world Asks for something different.",
  "Not every chapter closes with clarity, Some end Because you finally choose peace.",
  "Discipline grows stronger When it comes from self-respect Instead of fear.",
  "You don't outgrow problems, You outgrow the version of you That couldn't handle them yet.",
  "Rest is productive When it prevents you From breaking yourself.",
  "You are not weak for feeling deeply, Sensitivity is awareness Without emotional armor.",
  "Sometimes the bravest thing Is to slow down When everything tells you to rush.",
  "Healing takes time Because trust—especially with yourself— Takes time to rebuild.",
  "You don't need to be perfect, You need to be present With honest effort.",
  "Love should feel like safety, Not confusion, Not constant self-doubt.",
  "The right people Make space for your emotions Instead of minimizing them.",
  "Love grows Where communication is honest And egos are quiet.",
  "Healthy love does not drain you, It strengthens your sense of self Rather than replacing it.",
  "Real connection begins When you can be yourself Without performance.",
  "Some lessons repeat Until you stop blaming circumstances And start choosing differently.",
  "Your worth does not decrease Because someone failed to see it, It was never theirs to define.",
  "You don't need approval To trust your own experience, Your feelings are valid.",
  "Life becomes lighter When you stop carrying expectations That were never yours.",
  "Growth feels lonely sometimes Because comfort rarely lives Where transformation happens.",
  "Mental peace is built By small boundaries respected daily, Not big decisions made once.",
  "You don't heal by ignoring pain, You heal by facing it Without letting it control you.",
  "Your inner dialogue matters, It becomes the environment Where your future grows.",
  "You are not falling behind, You are learning At a pace that suits your life.",
  "Consistency matters more Than intensity When building a sustainable life.",
  "Some days survival is success, Even if nothing else Gets done.",
  "You don't need to have it all figured out, You only need enough clarity To take the next step.",
  "Your nervous system remembers What your mind tries to forget, Be kind to both.",
  "Not all progress looks impressive, Some looks like saying no For the first time.",
  "Emotional maturity begins When you stop reacting And start responding.",
  "You are allowed to rest Even if others don't understand Your exhaustion.",
  "Sometimes peace requires distance, Not explanation, Not justification.",
  "Your energy is valuable, Spend it where it is respected And returned.",
  "You don't owe productivity At the cost Of your mental health.",
  "Self-trust is built When your actions align With your values.",
  "Love yourself enough To walk away from what Keeps hurting you.",
  "Not every emotion needs to be solved, Some just need To be felt safely.",
  "Your past shaped you, But it does not get To decide your future.",
  "You grow stronger When you stop abandoning yourself To please others.",
  "Life feels clearer When your choices match What you truly need.",
  "Burnout happens quietly, Listen to the early signs Before they become demands.",
  "You are allowed to want more Without hating What you already have.",
  "Healing isn't linear, Some days you move forward, Some days you rest.",
  "Peace is choosing What aligns with you Even when it disappoints others.",
  "You don't need to rush healing, Your nervous system Moves at its own pace.",
  "Self-care is not indulgence, It is maintenance For a human life.",
  "Clarity comes When you stop overthinking And start observing.",
  "You are not responsible For fixing everyone, Including those you love.",
  "The strongest boundaries Are enforced quietly Without anger.",
  "Confidence grows When you keep promises To yourself.",
  "Some relationships teach love, Some teach boundaries, Both are valuable.",
  "Your emotions don't make you weak, They make you aware Of your inner world.",
  "Peace begins When you stop explaining yourself To people who refuse to listen.",
  "You don't have to earn rest, You deserve it Because you exist.",
  "Your healing journey Is not behind schedule, It is personal.",
  "Not everything requires your reaction, Silence can also be A powerful response.",
  "You grow when you choose clarity Over comfort Again and again.",
  "Let go of what drains you, Not everything deserves Your emotional energy.",
  "You are allowed to outgrow People, habits, And old versions of yourself.",
  "Progress is built Through patience with yourself On difficult days.",
  "Love should add calm, Not anxiety To your life.",
  "You don't need to prove your pain, Feeling it is already real Enough.",
  "Your inner peace Is more valuable Than winning arguments.",
  "Growth happens When your actions match Your awareness.",
  "You are allowed to protect Your mental space Without feeling guilty.",
  "Some clarity comes only After you stop forcing answers And allow time.",
  "You don't need to be fearless, You need to be honest And consistent.",
  "Your life changes When you change What you tolerate.",
  "Healing begins When you stop criticizing Your coping mechanisms.",
  "You are learning how to live, Mistakes are part Of the curriculum.",
  "Emotional safety Is the foundation Of all healthy relationships.",
  "You are not too sensitive, You are simply aware Of emotional impact.",
  "Peace grows When expectations are communicated Instead of assumed.",
  "Your needs matter Even if they make others uncomfortable.",
  "You don't lose yourself overnight, You drift away slowly By ignoring your voice.",
  "Healing asks for patience, Not pressure, Not perfection.",
  "You are allowed to start over As many times as needed, Without shame.",
  "Your growth does not need To look impressive To be meaningful.",
  "You don't need to rush success, A stable foundation Lasts longer.",
  "Inner peace is built By choosing alignment Over approval.",
  "Sometimes closure comes From understanding yourself, Not from others.",
  "You are allowed to change Your mind As you grow.",
  "Mental strength includes Asking for help When needed.",
  "Your emotions are valid, Even when others Don't understand them.",
  "You don't need external validation When you learn To trust yourself.",
  "Healing doesn't erase scars, It teaches you How to live without fear of them.",
  "Your time is limited, Spend it Where it feels meaningful.",
  "You are not difficult to love, You simply need The right environment.",
  "Peace is not found, It is built Through daily choices.",
  "You are becoming someone Who listens to themselves And acts with intention.",
];

export function getRandomQuote(): string {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

export function getQuoteByIndex(index: number): string {
  return quotes[index % quotes.length];
}
