'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'zh' | 'hi' | 'ar' | 'fr' | 'de' | 'ja' | 'pt' | 'ru' | 'ko' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'app.name': 'Reveura',
    'app.tagline': 'Mental Wellness Habit Tracker',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    
    // Auth
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createAccount': 'Create now',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.continueWith': 'OR CONTINUE WITH',
    'auth.agree': 'By continuing, you agree to our',
    'auth.terms': 'Terms',
    'auth.privacy': 'Privacy Policy',
    'auth.welcome': 'Welcome to Reveura',
    'auth.welcomeBack': 'Welcome Back',
    'auth.description': 'Track your mood, habits, sleep & reflections. Understand your emotional patterns and build balanced well-being through awareness.',
    'auth.features.security': 'Bank-level security',
    'auth.features.performance': 'Lightning-fast performance',
    'auth.features.experience': 'Premium experience',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.journal': 'Journal',
    'nav.habits': 'Habits',
    'nav.sleep': 'Sleep Log',
    'nav.games': 'Mood Games',
    'nav.inspiration': 'Inspiration',
    'nav.achievements': 'Achievements',
    'nav.insights': 'Insights',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.moodToday': "How's your mood today?",
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.stats': 'Your Stats',
    'dashboard.streak': 'Current Streak',
    'dashboard.entries': 'Journal Entries',
    'dashboard.habits': 'Active Habits',
    'dashboard.hours': 'Avg Sleep',
    
    // Journal
    'journal.title': 'My Journey',
    'journal.subtitle': 'Capture your thoughts, feelings, and memories',
    'journal.newEntry': 'New Entry',
    'journal.createEntry': 'Create New Entry',
    'journal.editEntry': 'Edit Entry',
    'journal.noEntries': 'No entries yet',
    'journal.startJourney': 'Start your journaling journey',
    'journal.createFirst': 'Create First Entry',
    'journal.mood': 'How are you feeling?',
    'journal.weather': 'Weather Today',
    'journal.title.label': 'Title',
    'journal.content': 'Your Thoughts',
    'journal.tags': 'Tags',
    'journal.addTag': 'Add a tag...',
    'journal.private': 'Private Entry',
    'journal.public': 'Public Entry',
    'journal.saveEntry': 'Save Entry',
    'journal.updateEntry': 'Update Entry',
    'journal.analytics': 'Analytics',
    'journal.moodDistribution': 'Mood Distribution',
    'journal.sentiment': 'Average Sentiment',
    'journal.energy': 'Average Energy',
    'journal.favorites': 'favorites',
    'journal.entries': 'entries',
    'journal.gridView': 'Grid',
    'journal.timelineView': 'Timeline',
    'journal.calendarView': 'Calendar',
    'journal.filterMood': 'FILTER BY MOOD',
    'journal.allMoods': 'All Moods',
    'journal.read': 'Read',
    'journal.characters': 'characters',
    
    // Moods
    'mood.amazing': 'Amazing',
    'mood.happy': 'Happy',
    'mood.calm': 'Calm',
    'mood.neutral': 'Neutral',
    'mood.anxious': 'Anxious',
    'mood.sad': 'Sad',
    
    // Habits
    'habits.title': 'Habit Tracker',
    'habits.subtitle': 'Build lasting routines, one day at a time',
    'habits.addHabit': 'Add Habit',
    'habits.createHabit': 'Create New Habit',
    'habits.editHabit': 'Edit Habit',
    'habits.noHabits': 'No habits yet',
    'habits.startBuilding': 'Start building better habits today',
    'habits.createFirst': 'Create Your First Habit',
    'habits.name': 'Habit Name',
    'habits.description': 'Description',
    'habits.category': 'Category',
    'habits.icon': 'Icon',
    'habits.weeklyTarget': 'Weekly Target',
    'habits.reminderTime': 'Reminder Time (Optional)',
    'habits.activeHabits': 'Active Habits',
    'habits.bestStreak': 'Best Streak',
    'habits.completion': 'Completion',
    'habits.totalPoints': 'Total Points',
    'habits.weekView': 'Week View',
    'habits.monthView': 'Month View',
    'habits.streakView': 'Streak View',
    'habits.currentStreak': 'Current Streak',
    'habits.favorites': 'favorites',
    
    // Categories
    'category.health': 'Health',
    'category.mindfulness': 'Mindfulness',
    'category.fitness': 'Fitness',
    'category.learning': 'Learning',
    'category.productivity': 'Productivity',
    'category.creative': 'Creative',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Control your privacy, customize reminders, and manage your wellness data',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.preferences': 'Preferences',
    'settings.privacy': 'Privacy & Data',
    'settings.appPreferences': 'App Preferences',
    'settings.customize': 'Customize your experience',
    'settings.theme': 'Theme',
    'settings.dark': 'Dark',
    'settings.darkDesc': 'Easy on the eyes',
    'settings.light': 'Light',
    'settings.lightDesc': 'Bright and clear',
    'settings.language': 'Language',
    'settings.weekStarts': 'Week Starts On',
    'settings.sunday': 'Sunday',
    'settings.monday': 'Monday',
    'settings.unsavedChanges': 'You have unsaved changes',
    'settings.discard': 'Discard',
    'settings.saveChanges': 'Save Changes',
    
    // Tour
    'tour.welcome.title': 'Welcome to Reveura!',
    'tour.welcome.description': 'Your premium mental wellness companion. Let me show you around!',
    'tour.dashboard.title': 'Your Dashboard',
    'tour.dashboard.description': 'Track your mood, habits, and progress all in one place. Your wellness journey starts here!',
    'tour.journal.title': 'Journal',
    'tour.journal.description': 'Express your thoughts and track your emotional journey. Your personal space for reflection.',
    'tour.habits.title': 'Habits',
    'tour.habits.description': 'Build positive habits and track your daily routines. Small steps lead to big changes!',
    'tour.mood.title': 'Mood Tracking',
    'tour.mood.description': 'Log your daily mood and understand your emotional patterns over time.',
    'tour.settings.title': 'Settings',
    'tour.settings.description': 'Customize your experience, change languages, themes, and manage your profile.',
    'tour.complete.title': 'You\'re All Set!',
    'tour.complete.description': 'Start your wellness journey today. Remember, progress is more important than perfection!',
    
    // Days of week
    'day.sun': 'Sun',
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sunday': 'Sunday',
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wednesday': 'Wednesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',
  },
  
  es: {
    // Common
    'app.name': 'Reveura',
    'app.tagline': 'Rastreador de Hábitos de Bienestar Mental',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Añadir',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.confirm': 'Confirmar',
    'common.loading': 'Cargando...',
    
    // Auth
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.rememberMe': 'Recuérdame',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.createAccount': 'Crear ahora',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.continueWith': 'O CONTINUAR CON',
    'auth.agree': 'Al continuar, aceptas nuestros',
    'auth.terms': 'Términos',
    'auth.privacy': 'Política de Privacidad',
    'auth.welcome': 'Bienvenido a Reveura',
    'auth.welcomeBack': 'Bienvenido de nuevo',
    'auth.description': 'Rastrea tu estado de ánimo, hábitos, sueño y reflexiones. Comprende tus patrones emocionales y construye bienestar equilibrado a través de la conciencia.',
    'auth.features.security': 'Seguridad bancaria',
    'auth.features.performance': 'Rendimiento ultrarrápido',
    'auth.features.experience': 'Experiencia premium',
    
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.journal': 'Diario',
    'nav.habits': 'Hábitos',
    'nav.sleep': 'Registro de Sueño',
    'nav.games': 'Juegos de Ánimo',
    'nav.inspiration': 'Inspiración',
    'nav.achievements': 'Logros',
    'nav.insights': 'Perspectivas',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.moodToday': '¿Cómo está tu ánimo hoy?',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.stats': 'Tus Estadísticas',
    'dashboard.streak': 'Racha Actual',
    'dashboard.entries': 'Entradas de Diario',
    'dashboard.habits': 'Hábitos Activos',
    'dashboard.hours': 'Sueño Promedio',
    
    // Journal
    'journal.title': 'Mi Viaje',
    'journal.subtitle': 'Captura tus pensamientos, sentimientos y recuerdos',
    'journal.newEntry': 'Nueva Entrada',
    'journal.createEntry': 'Crear Nueva Entrada',
    'journal.editEntry': 'Editar Entrada',
    'journal.noEntries': 'Aún no hay entradas',
    'journal.startJourney': 'Comienza tu viaje de diario',
    'journal.createFirst': 'Crear Primera Entrada',
    'journal.mood': '¿Cómo te sientes?',
    'journal.weather': 'Clima Hoy',
    'journal.title.label': 'Título',
    'journal.content': 'Tus Pensamientos',
    'journal.tags': 'Etiquetas',
    'journal.addTag': 'Añadir etiqueta...',
    'journal.private': 'Entrada Privada',
    'journal.public': 'Entrada Pública',
    'journal.saveEntry': 'Guardar Entrada',
    'journal.updateEntry': 'Actualizar Entrada',
    'journal.analytics': 'Análisis',
    'journal.moodDistribution': 'Distribución de Ánimo',
    'journal.sentiment': 'Sentimiento Promedio',
    'journal.energy': 'Energía Promedia',
    'journal.favorites': 'favoritos',
    'journal.entries': 'entradas',
    'journal.gridView': 'Cuadrícula',
    'journal.timelineView': 'Línea de Tiempo',
    'journal.calendarView': 'Calendario',
    'journal.filterMood': 'FILTRAR POR ÁNIMO',
    'journal.allMoods': 'Todos los Ánimos',
    'journal.read': 'Leer',
    'journal.characters': 'caracteres',
    
    // Moods
    'mood.amazing': 'Increíble',
    'mood.happy': 'Feliz',
    'mood.calm': 'Tranquilo',
    'mood.neutral': 'Neutral',
    'mood.anxious': 'Ansioso',
    'mood.sad': 'Triste',
    
    // Habits
    'habits.title': 'Rastreador de Hábitos',
    'habits.subtitle': 'Construye rutinas duraderas, un día a la vez',
    'habits.addHabit': 'Añadir Hábito',
    'habits.createHabit': 'Crear Nuevo Hábito',
    'habits.editHabit': 'Editar Hábito',
    'habits.noHabits': 'Aún no hay hábitos',
    'habits.startBuilding': 'Comienza a construir mejores hábitos hoy',
    'habits.createFirst': 'Crea Tu Primer Hábito',
    'habits.name': 'Nombre del Hábito',
    'habits.description': 'Descripción',
    'habits.category': 'Categoría',
    'habits.icon': 'Icono',
    'habits.weeklyTarget': 'Objetivo Semanal',
    'habits.reminderTime': 'Hora de Recordatorio (Opcional)',
    'habits.activeHabits': 'Hábitos Activos',
    'habits.bestStreak': 'Mejor Racha',
    'habits.completion': 'Finalización',
    'habits.totalPoints': 'Puntos Totales',
    'habits.weekView': 'Vista Semanal',
    'habits.monthView': 'Vista Mensual',
    'habits.streakView': 'Vista de Rachas',
    'habits.currentStreak': 'Racha Actual',
    'habits.favorites': 'favoritos',
    
    // Categories
    'category.health': 'Salud',
    'category.mindfulness': 'Atención Plena',
    'category.fitness': 'Fitness',
    'category.learning': 'Aprendizaje',
    'category.productivity': 'Productividad',
    'category.creative': 'Creativo',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Controla tu privacidad, personaliza recordatorios y gestiona tus datos de bienestar',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificaciones',
    'settings.preferences': 'Preferencias',
    'settings.privacy': 'Privacidad y Datos',
    'settings.appPreferences': 'Preferencias de la Aplicación',
    'settings.customize': 'Personaliza tu experiencia',
    'settings.theme': 'Tema',
    'settings.dark': 'Oscuro',
    'settings.darkDesc': 'Suave para los ojos',
    'settings.light': 'Claro',
    'settings.lightDesc': 'Brillante y claro',
    'settings.language': 'Idioma',
    'settings.weekStarts': 'La Semana Comienza El',
    'settings.sunday': 'Domingo',
    'settings.monday': 'Lunes',
    'settings.unsavedChanges': 'Tienes cambios sin guardar',
    'settings.discard': 'Descartar',
    'settings.saveChanges': 'Guardar Cambios',
    
    // Days of week
    'day.sun': 'Dom',
    'day.mon': 'Lun',
    'day.tue': 'Mar',
    'day.wed': 'Mié',
    'day.thu': 'Jue',
    'day.fri': 'Vie',
    'day.sat': 'Sáb',
    'day.sunday': 'Domingo',
    'day.monday': 'Lunes',
    'day.tuesday': 'Martes',
    'day.wednesday': 'Miércoles',
    'day.thursday': 'Jueves',
    'day.friday': 'Viernes',
    'day.saturday': 'Sábado',
  },
  
  zh: {
    // Common
    'app.name': 'Reveura',
    'app.tagline': '心理健康习惯追踪器',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.close': '关闭',
    'common.back': '返回',
    'common.next': '下一个',
    'common.previous': '上一个',
    'common.confirm': '确认',
    'common.loading': '加载中...',
    
    // Auth
    'auth.signin': '登录',
    'auth.signup': '注册',
    'auth.email': '电子邮件地址',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.rememberMe': '记住我',
    'auth.forgotPassword': '忘记密码？',
    'auth.createAccount': '立即创建',
    'auth.noAccount': '没有账户？',
    'auth.haveAccount': '已有账户？',
    'auth.continueWith': '或继续使用',
    'auth.agree': '继续即表示您同意我们的',
    'auth.terms': '条款',
    'auth.privacy': '隐私政策',
    'auth.welcome': '欢迎来到 Reveura',
    'auth.welcomeBack': '欢迎回来',
    'auth.description': '追踪您的情绪、习惯、睡眠和反思。了解您的情绪模式，通过意识建立平衡的幸福感。',
    'auth.features.security': '银行级安全',
    'auth.features.performance': '闪电般快速',
    'auth.features.experience': '优质体验',
    
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.journal': '日记',
    'nav.habits': '习惯',
    'nav.sleep': '睡眠日志',
    'nav.games': '情绪游戏',
    'nav.inspiration': '灵感',
    'nav.achievements': '成就',
    'nav.insights': '见解',
    'nav.settings': '设置',
    'nav.logout': '登出',
    
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.moodToday': '今天心情如何？',
    'dashboard.quickActions': '快速操作',
    'dashboard.recentActivity': '最近活动',
    'dashboard.stats': '您的统计',
    'dashboard.streak': '当前连续',
    'dashboard.entries': '日记条目',
    'dashboard.habits': '活跃习惯',
    'dashboard.hours': '平均睡眠',
    
    // Journal
    'journal.title': '我的旅程',
    'journal.subtitle': '记录您的想法、感受和回忆',
    'journal.newEntry': '新条目',
    'journal.createEntry': '创建新条目',
    'journal.editEntry': '编辑条目',
    'journal.noEntries': '还没有条目',
    'journal.startJourney': '开始您的日记之旅',
    'journal.createFirst': '创建第一个条目',
    'journal.mood': '您感觉如何？',
    'journal.weather': '今日天气',
    'journal.title.label': '标题',
    'journal.content': '您的想法',
    'journal.tags': '标签',
    'journal.addTag': '添加标签...',
    'journal.private': '私密条目',
    'journal.public': '公开条目',
    'journal.saveEntry': '保存条目',
    'journal.updateEntry': '更新条目',
    'journal.analytics': '分析',
    'journal.moodDistribution': '情绪分布',
    'journal.sentiment': '平均情感',
    'journal.energy': '平均能量',
    'journal.favorites': '收藏',
    'journal.entries': '条目',
    'journal.gridView': '网格',
    'journal.timelineView': '时间线',
    'journal.calendarView': '日历',
    'journal.filterMood': '按情绪筛选',
    'journal.allMoods': '所有情绪',
    'journal.read': '阅读',
    'journal.characters': '字符',
    
    // Moods
    'mood.amazing': '太棒了',
    'mood.happy': '快乐',
    'mood.calm': '平静',
    'mood.neutral': '中性',
    'mood.anxious': '焦虑',
    'mood.sad': '悲伤',
    
    // Habits
    'habits.title': '习惯追踪器',
    'habits.subtitle': '一天一个习惯，建立持久的日常',
    'habits.addHabit': '添加习惯',
    'habits.createHabit': '创建新习惯',
    'habits.editHabit': '编辑习惯',
    'habits.noHabits': '还没有习惯',
    'habits.startBuilding': '今天开始建立更好的习惯',
    'habits.createFirst': '创建您的第一个习惯',
    'habits.name': '习惯名称',
    'habits.description': '描述',
    'habits.category': '类别',
    'habits.icon': '图标',
    'habits.weeklyTarget': '每周目标',
    'habits.reminderTime': '提醒时间（可选）',
    'habits.activeHabits': '活跃习惯',
    'habits.bestStreak': '最佳连续',
    'habits.completion': '完成度',
    'habits.totalPoints': '总积分',
    'habits.weekView': '周视图',
    'habits.monthView': '月视图',
    'habits.streakView': '连续视图',
    'habits.currentStreak': '当前连续',
    'habits.favorites': '收藏',
    
    // Categories
    'category.health': '健康',
    'category.mindfulness': '正念',
    'category.fitness': '健身',
    'category.learning': '学习',
    'category.productivity': '生产力',
    'category.creative': '创意',
    
    // Settings
    'settings.title': '设置',
    'settings.subtitle': '控制您的隐私，自定义提醒，管理您的健康数据',
    'settings.profile': '个人资料',
    'settings.notifications': '通知',
    'settings.preferences': '偏好设置',
    'settings.privacy': '隐私与数据',
    'settings.appPreferences': '应用偏好',
    'settings.customize': '自定义您的体验',
    'settings.theme': '主题',
    'settings.dark': '深色',
    'settings.darkDesc': '护眼模式',
    'settings.light': '浅色',
    'settings.lightDesc': '明亮清晰',
    'settings.language': '语言',
    'settings.weekStarts': '周开始于',
    'settings.sunday': '星期日',
    'settings.monday': '星期一',
    'settings.unsavedChanges': '您有未保存的更改',
    'settings.discard': '放弃',
    'settings.saveChanges': '保存更改',
    
    // Days of week
    'day.sun': '日',
    'day.mon': '一',
    'day.tue': '二',
    'day.wed': '三',
    'day.thu': '四',
    'day.fri': '五',
    'day.sat': '六',
    'day.sunday': '星期日',
    'day.monday': '星期一',
    'day.tuesday': '星期二',
    'day.wednesday': '星期三',
    'day.thursday': '星期四',
    'day.friday': '星期五',
    'day.saturday': '星期六',
  },
  
  hi: {
    // Common
    'app.name': 'Reveura',
    'app.tagline': 'मानसिक कल्याण आदत ट्रैकर',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.confirm': 'पुष्टि करें',
    'common.loading': 'लोड हो रहा है...',
    
    // Auth
    'auth.signin': 'साइन इन करें',
    'auth.signup': 'साइन अप करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.createAccount': 'अब बनाएं',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.haveAccount': 'पहले से खाता है?',
    'auth.continueWith': 'या जारी रखें',
    'auth.agree': 'जारी रखकर, आप हमारी सहमति देते हैं',
    'auth.terms': 'शर्तें',
    'auth.privacy': 'गोपनीयता नीति',
    'auth.welcome': 'Reveura में आपका स्वागत है',
    'auth.welcomeBack': 'वापसी पर स्वागत है',
    'auth.description': 'अपने मूड, आदतों, नींद और चिंतन को ट्रैक करें। अपने भावनात्मक पैटर्न को समझें और जागरूकता के माध्यम से संतुलित कल्याण का निर्माण करें।',
    'auth.features.security': 'बैंक-स्तरीय सुरक्षा',
    'auth.features.performance': 'बिजली की तेज़ गति',
    'auth.features.experience': 'प्रीमियम अनुभव',
    
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.journal': 'डायरी',
    'nav.habits': 'आदतें',
    'nav.sleep': 'नींद लॉग',
    'nav.games': 'मूड गेम्स',
    'nav.inspiration': 'प्रेरणा',
    'nav.achievements': 'उपलब्धियां',
    'nav.insights': 'अंतर्दृष्टि',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉग आउट',
    
    // Dashboard
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.moodToday': 'आज आपका मूड कैसा है?',
    'dashboard.quickActions': 'त्वरित क्रियाएं',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'dashboard.stats': 'आपके आंकड़े',
    'dashboard.streak': 'वर्तमान स्ट्रीक',
    'dashboard.entries': 'डायरी प्रविष्टियां',
    'dashboard.habits': 'सक्रिय आदतें',
    'dashboard.hours': 'औसत नींद',
    
    // Journal
    'journal.title': 'मेरी यात्रा',
    'journal.subtitle': 'अपने विचारों, भावनाओं और यादों को कैप्चर करें',
    'journal.newEntry': 'नई प्रविष्टि',
    'journal.createEntry': 'नई प्रविष्टि बनाएं',
    'journal.editEntry': 'प्रविष्टि संपादित करें',
    'journal.noEntries': 'अभी तक कोई प्रविष्टि नहीं',
    'journal.startJourney': 'अपनी डायरी यात्रा शुरू करें',
    'journal.createFirst': 'पहली प्रविष्टि बनाएं',
    'journal.mood': 'आप कैसा महसूस कर रहे हैं?',
    'journal.weather': 'आज का मौसम',
    'journal.title.label': 'शीर्षक',
    'journal.content': 'आपके विचार',
    'journal.tags': 'टैग',
    'journal.addTag': 'टैग जोड़ें...',
    'journal.private': 'निजी प्रविष्टि',
    'journal.public': 'सार्वजनिक प्रविष्टि',
    'journal.saveEntry': 'प्रविष्टि सहेजें',
    'journal.updateEntry': 'प्रविष्टि अपडेट करें',
    'journal.analytics': 'विश्लेषण',
    'journal.moodDistribution': 'मूड वितरण',
    'journal.sentiment': 'औसत भावना',
    'journal.energy': 'औसत ऊर्जा',
    'journal.favorites': 'पसंदीदा',
    'journal.entries': 'प्रविष्टियां',
    'journal.gridView': 'ग्रिड',
    'journal.timelineView': 'टाइमलाइन',
    'journal.calendarView': 'कैलेंडर',
    'journal.filterMood': 'मूड द्वारा फ़िल्टर करें',
    'journal.allMoods': 'सभी मूड',
    'journal.read': 'पढ़ें',
    'journal.characters': 'अक्षर',
    
    // Moods
    'mood.amazing': 'अद्भुत',
    'mood.happy': 'खुश',
    'mood.calm': 'शांत',
    'mood.neutral': 'तटस्थ',
    'mood.anxious': 'चिंतित',
    'mood.sad': 'उदास',
    
    // Habits
    'habits.title': 'आदत ट्रैकर',
    'habits.subtitle': 'एक समय में एक दिन, स्थायी दिनचर्या बनाएं',
    'habits.addHabit': 'आदत जोड़ें',
    'habits.createHabit': 'नई आदत बनाएं',
    'habits.editHabit': 'आदत संपादित करें',
    'habits.noHabits': 'अभी तक कोई आदत नहीं',
    'habits.startBuilding': 'आज बेहतर आदतें बनाना शुरू करें',
    'habits.createFirst': 'अपनी पहली आदत बनाएं',
    'habits.name': 'आदत का नाम',
    'habits.description': 'विवरण',
    'habits.category': 'श्रेणी',
    'habits.icon': 'आइकन',
    'habits.weeklyTarget': 'साप्ताहिक लक्ष्य',
    'habits.reminderTime': 'अनुस्मारक समय (वैकल्पिक)',
    'habits.activeHabits': 'सक्रिय आदतें',
    'habits.bestStreak': 'सर्वश्रेष्ठ स्ट्रीक',
    'habits.completion': 'पूर्णता',
    'habits.totalPoints': 'कुल अंक',
    'habits.weekView': 'सप्ताह दृश्य',
    'habits.monthView': 'महीना दृश्य',
    'habits.streakView': 'स्ट्रीक दृश्य',
    'habits.currentStreak': 'वर्तमान स्ट्रीक',
    'habits.favorites': 'पसंदीदा',
    
    // Categories
    'category.health': 'स्वास्थ्य',
    'category.mindfulness': 'सचेतनता',
    'category.fitness': 'फिटनेस',
    'category.learning': 'सीखना',
    'category.productivity': 'उत्पादकता',
    'category.creative': 'रचनात्मक',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपनी गोपनीयता को नियंत्रित करें, अनुस्मारक अनुकूलित करें, और अपने कल्याण डेटा का प्रबंधन करें',
    'settings.profile': 'प्रोफ़ाइल',
    'settings.notifications': 'सूचनाएं',
    'settings.preferences': 'प्राथमिकताएं',
    'settings.privacy': 'गोपनीयता और डेटा',
    'settings.appPreferences': 'ऐप प्राथमिकताएं',
    'settings.customize': 'अपने अनुभव को अनुकूलित करें',
    'settings.theme': 'थीम',
    'settings.dark': 'डार्क',
    'settings.darkDesc': 'आंखों के लिए आसान',
    'settings.light': 'लाइट',
    'settings.lightDesc': 'उज्ज्वल और स्पष्ट',
    'settings.language': 'भाषा',
    'settings.weekStarts': 'सप्ताह की शुरुआत',
    'settings.sunday': 'रविवार',
    'settings.monday': 'सोमवार',
    'settings.unsavedChanges': 'आपके पास असहेजे परिवर्तन हैं',
    'settings.discard': 'त्यागें',
    'settings.saveChanges': 'परिवर्तन सहेजें',
    
    // Days of week
    'day.sun': 'रवि',
    'day.mon': 'सोम',
    'day.tue': 'मंगल',
    'day.wed': 'बुध',
    'day.thu': 'गुरु',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sunday': 'रविवार',
    'day.monday': 'सोमवार',
    'day.tuesday': 'मंगलवार',
    'day.wednesday': 'बुधवार',
    'day.thursday': 'गुरुवार',
    'day.friday': 'शुक्रवार',
    'day.saturday': 'शनिवार',
  },
  
  // Add simplified translations for other languages
  ar: { 'app.name': 'Reveura', 'auth.signin': 'تسجيل الدخول', 'auth.signup': 'التسجيل', 'common.save': 'حفظ', 'common.cancel': 'إلغاء', 'nav.dashboard': 'لوحة التحكم', 'nav.journal': 'المذكرات', 'nav.habits': 'العادات', 'nav.settings': 'الإعدادات', 'settings.language': 'اللغة', 'settings.theme': 'المظهر' },
  fr: { 'app.name': 'Reveura', 'auth.signin': 'Se connecter', 'auth.signup': 'S\'inscrire', 'common.save': 'Enregistrer', 'common.cancel': 'Annuler', 'nav.dashboard': 'Tableau de bord', 'nav.journal': 'Journal', 'nav.habits': 'Habitudes', 'nav.settings': 'Paramètres', 'settings.language': 'Langue', 'settings.theme': 'Thème' },
  de: { 'app.name': 'Reveura', 'auth.signin': 'Anmelden', 'auth.signup': 'Registrieren', 'common.save': 'Speichern', 'common.cancel': 'Abbrechen', 'nav.dashboard': 'Dashboard', 'nav.journal': 'Tagebuch', 'nav.habits': 'Gewohnheiten', 'nav.settings': 'Einstellungen', 'settings.language': 'Sprache', 'settings.theme': 'Design' },
  ja: { 'app.name': 'Reveura', 'auth.signin': 'サインイン', 'auth.signup': 'サインアップ', 'common.save': '保存', 'common.cancel': 'キャンセル', 'nav.dashboard': 'ダッシュボード', 'nav.journal': '日記', 'nav.habits': '習慣', 'nav.settings': '設定', 'settings.language': '言語', 'settings.theme': 'テーマ' },
  pt: { 'app.name': 'Reveura', 'auth.signin': 'Entrar', 'auth.signup': 'Cadastrar', 'common.save': 'Salvar', 'common.cancel': 'Cancelar', 'nav.dashboard': 'Painel', 'nav.journal': 'Diário', 'nav.habits': 'Hábitos', 'nav.settings': 'Configurações', 'settings.language': 'Idioma', 'settings.theme': 'Tema' },
  ru: { 'app.name': 'Reveura', 'auth.signin': 'Войти', 'auth.signup': 'Регистрация', 'common.save': 'Сохранить', 'common.cancel': 'Отмена', 'nav.dashboard': 'Панель', 'nav.journal': 'Дневник', 'nav.habits': 'Привычки', 'nav.settings': 'Настройки', 'settings.language': 'Язык', 'settings.theme': 'Тема' },
  ko: { 'app.name': 'Reveura', 'auth.signin': '로그인', 'auth.signup': '가입', 'common.save': '저장', 'common.cancel': '취소', 'nav.dashboard': '대시보드', 'nav.journal': '일기', 'nav.habits': '습관', 'nav.settings': '설정', 'settings.language': '언어', 'settings.theme': '테마' },
  it: { 'app.name': 'Reveura', 'auth.signin': 'Accedi', 'auth.signup': 'Registrati', 'common.save': 'Salva', 'common.cancel': 'Annulla', 'nav.dashboard': 'Dashboard', 'nav.journal': 'Diario', 'nav.habits': 'Abitudini', 'nav.settings': 'Impostazioni', 'settings.language': 'Lingua', 'settings.theme': 'Tema' },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('reveura_language');
    if (stored && languages.some(l => l.code === stored)) {
      setLanguageState(stored as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('reveura_language', lang);
    
    // Update document direction for RTL languages
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
